### PR TITLE
Update readme files

### LINKED ISSUE #743: Update README files
Most `README.md` files are outdated and no longer match the available command line options and arguments. 

- **Indexer-Agent**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/README.md) vs CLI structure ([single-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start.ts), [multi-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start-multi-network.ts), [shared](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/common-options.ts))
- **Indexer-Service**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-service/README.md) vs [CLI structure](https://github.com/graphprotocol/indexer/blob/93694eeb2cea19abebee0e547b8ad992c6b462dd/packages/indexer-service/src/commands/start.ts#L41-L178)
- **Indexer-CLI**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-cli/README.md) vs [CLI (module-based) structure](https://github.com/graphprotocol/indexer/tree/main/packages/indexer-cli/src/commands)

### PR DESCRIPTION
**Pull request by nikhilverma360**
## Explanation

Fixes #743 

**Problem**: Most README.md files are outdated and no longer match the available command line options and arguments.
**Solution** : 
- Updated graph-indexer README.md
- Updated indexer-service README.md
- Updated indexer-agent README.md

## Pre-merge  checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
- [x] Tested command line options locally

### CODE REVIEW

**Comment by nikhilverma360** [comment]
## References / Double Checks ✅:
### Updated graph-indexer README.md ✅

updated / added 3 `graph indexer --help` (stdout) commands  a according to [indexer-help.stdout](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-cli/src/__tests__/references/indexer-help.stdout)

`indexer cost delete            Remove one or many cost models`
`indexer actions update         Update one or more actions`
`indexer actions delete         Delete one or many actions in the queue`

### Updated indexer-service README.md ✅

References: [start.ts]( https://github.com/graphprotocol/indexer/blob/93694eeb2cea19abebee0e547b8ad992c6b462dd/packages/indexer-service/src/commands/start.ts#L41-L178)

Double check via Local run
Screenshot 2023-08-30 at 11 35 12 AM


### Updated indexer-agent README.md ✅

References : [single-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start.ts), [multi-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start-multi-network.ts), [shared](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/common-options.ts)


Double Check by running Locally: 
Screenshot 2023-08-30 at 3 59 09 PM

Screenshot 2023-08-30 at 3 59 54 PM

**Comment by nikhilverma360** [comment]
@tilacog waiting for the approval !

**Review by tilacog — APPROVED** [review]
Looks great! Thanks a lot!
I just added a (rather occult) section for the Indexer Agent and sorted the Indexer CLI lines alphabetically.

**Comment by nikhilverma360** [comment]
Thanks @tilacog  🔥

**Pull request merged**
