### PR TITLE
common: Remove failed subgraph check

### PR DESCRIPTION
**Pull request by dwerner**
Recreating #983 for @datanexus-vincent so CI can run on this.

### CODE REVIEW

**Review by fordN — APPROVED** [review]
👍

**Comment by fordN** [comment]
Approved! Can we update commit message to match our format before merging?

**Comment by datanexus-vincent** [comment]
> Approved! Can we update commit message to match our format before merging?

Pushed a new commit message on [my branch](https://github.com/datanexus-vincent/indexer/commit/0e10ce384ba9cbe212d9b25a33ec1b635f6656aa). I'll make sure to use the correct formatting for future PR commits. Thanks for approving!

**Comment by dwerner** [comment]
> > Approved! Can we update commit message to match our format before merging?
> 
> Pushed a new commit message on [my branch](https://github.com/datanexus-vincent/indexer/commit/0e10ce384ba9cbe212d9b25a33ec1b635f6656aa). I'll make sure to use the correct formatting for future PR commits. Thanks for approving!

Sorry, already took care of it here.

**Pull request merged**
