### PR TITLE
feat: check escrow balance before rav redeem

### LINKED ISSUE #1009: Don't redeem RAV if there's no escrow balance
In case indexers remove the denylist from an specific sender, indexer-agent shouldn't burn RAVs by sending them all at once.

We need a way to make sure that we only try to redeem RAVs if we have balance on their escrow account.

### PR DESCRIPTION
**Pull request by gusinacio**
Fixes #1009

### CODE REVIEW

**Comment by carlosvdr** [comment]
Looks good to me, but was this tested in any way?

**Comment by carlosvdr** [comment]
If there is any way to test through testnet or a local network would be nice to make sure this doesnt crash

**Comment by carlosvdr** [comment]
Perhaps some unit test 
Where you mock the tap Subgraph response for the escrow balance
To get the expected outcomes
One where it wont pass due to it not being enough and another test where it continues the desired path

**Comment by gusinacio** [comment]
Hey @carlosvdr and @dwerner could you give another review here?

**Comment by carlosvdr** [comment]
Oh yes this is nice! Works for me , great job :)

**Review by carlosvdr — APPROVED** [review]

**Review by dwerner — APPROVED** [review]

**Pull request merged**
