### PR TITLE
Add fantom to Caip2 list

### PR DESCRIPTION
**Pull request by trader-payne**

### CODE REVIEW

**Review by hopeyen — APPROVED** [review]

**Comment by hopeyen** [comment]
Looks good! Thanks Payne, feel free to merge whenever tests pass

**Comment by trader-payne** [comment]
@hopeyen added the trailing comma, needs approval again :|

**Comment by uzzer** [comment]
Any updates on this?

**Comment by uzzer** [comment]
Isn't it the same as https://github.com/graphprotocol/indexer/pull/641 ?

**Pull request closed without merging**
