### PR TITLE
fix: add pagination to tap collector

### LINKED ISSUE #1011: Add pagination to transaction retry logic
We have a system that checks for reverts and marks a transaction as final.

The problem happens in case someone has more than 100 redeem transactions pending. The system doesn't receive the transactions on this query because of pagination limits and assumes that it was reverted. It retries and the indexer keeps receiving a "Failed to redeem RAV" error message.

Here is the code where pagination logic must be implemented. https://github.com/graphprotocol/indexer/blob/ade405e07dd46e30dc4e7807417974133b87f2b0/packages/indexer-common/src/allocations/query-fees.ts#L656-L690

### PR DESCRIPTION
**Pull request by gusinacio**
Fixes #1011 

Depends on #1012

### CODE REVIEW

**Comment by carlosvdr** [comment]
Looks good but Id like seeing some sort of test or let us know if any test was done on your side for this

**Comment by dwerner** [comment]
> Looks good but Id like seeing some sort of test or let us know if any test was done on your side for this

@gusinacio was this addressed?

**Comment by gusinacio** [comment]
Hello @dwerner and @carlosvdr. I just tested everything. Could you review again?

**Review by carlosvdr — APPROVED** [review]
Nice this tests are great

**Review by dwerner — APPROVED** [review]

**Pull request merged**
