### PR TITLE
fix: optimize the round trips when reconciling the subgraph deployments 

### PR DESCRIPTION
**Pull request by abarmat**
## Issue

I was running the Indexer Agent and after a few days I realized the amount of queries it sent to the network subgraphs was out of proportion and quickly draining my api key.

## **Investigation**

The Indexer Agent performs a number of “housekeeping” queries at regular periods of time to sync with the latest network status.

One of those queries gets the entire set of subgraphs on the network but it does so paginating by 10 items batches. With the current number of subgraphs over 10,000, it takes more than 1,000 queries to get them all.

The eventual runs every 120 seconds, that means it's sending about 720,000 queries a day.

## Resolution

Set the `first` parameter to `1000` for the query within `subgraphDeployments` function of the `NetworkMonitor.`

### CODE REVIEW

**Review by dwerner — APPROVED** [review]
Good find. I have another PR in that was intended to fix a test in that same function (#1056), I bumped the page size there as well.

**Review by fordN — APPROVED** [review]
🙌

**Comment by dwerner** [comment]
closing in favor of https://github.com/graphprotocol/indexer/pull/1056, thanks!

**Comment by abarmat** [comment]
Also tagging @fordN for visibility

**Comment by dwerner** [comment]
My bad, I mixed up a similar fix.

**Pull request merged**
